#Het Shah
#25070126513
#AIML B1

In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from math import sqrt

In [54]:
df = sns.load_dataset('penguins')
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [55]:
df.dropna(inplace=True)
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [56]:
print(df['species'].unique())
print(df['island'].unique())

['Adelie' 'Chinstrap' 'Gentoo']
['Torgersen' 'Biscoe' 'Dream']

In [57]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['island'] = le.fit_transform(df['island'])
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,2,39.1,18.7,181.0,3750.0,1
1,Adelie,2,39.5,17.4,186.0,3800.0,0
2,Adelie,2,40.3,18.0,195.0,3250.0,0
4,Adelie,2,36.7,19.3,193.0,3450.0,0
5,Adelie,2,39.3,20.6,190.0,3650.0,1

In [58]:
X = df.drop('species', axis=1)
y = df['species']

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,stratify=y,random_state=20)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(X_train)
scaler.transform(X_val)

array([[-0.92688082, -1.05352899,  0.46571836, -1.17837771, -0.3071657 ,
         0.99250926],
       [ 0.47397315,  2.14048818,  1.32600367,  0.41456901, -0.24496085,
         0.99250926],
       [-0.92688082,  0.19867092, -1.35606229,  0.99382237,  0.99913625,
        -1.00754728],
       [-0.92688082,  0.90643609, -0.546382  ,  1.06622904,  1.68338966,
         0.99250926],
       [-0.92688082, -1.63425938,  0.36450832, -0.67153103, -0.58708755,
        -1.00754728],
       [-0.92688082, -1.14426811,  0.76934847, -1.54041106, -0.74259969,
         0.99250926],
       [ 0.47397315, -1.12612029,  0.46571836, -0.59912436, -0.55598512,
         0.99250926],
       [ 0.47397315, -0.79945944,  0.81995349, -0.81634437,  0.50149741,
         0.99250926],
       [ 0.47397315,  0.30755787,  0.06087822, -0.59912436, -0.74259969,
        -1.00754728],
       [ 0.47397315,  1.34198389,  0.92116352, -0.019871  , -0.3071657 ,
         0.99250926],
       [ 1.87482711, -1.59796373, -0.64759203, -1.10597104, -1.4268531 ,
        -1.00754728],
       [-0.92688082,  0.45274047, -1.35606229,  0.84900903,  0.25267799,
        -1.00754728],
       [ 0.47397315, -0.59983337, -0.09093684, -0.81634437, -0.58708755,
         0.99250926],
       [-0.92688082,  0.16237527, -1.71029741,  0.77660236,  0.68811198,
        -1.00754728],
       [ 0.47397315,  1.85012298,  1.83205385, -0.019871  ,  0.12826828,
         0.99250926],
       [ 0.47397315,  1.01532304,  0.51632338, -0.59912436, -0.5248827 ,
         0.99250926],
       [-0.92688082,  1.28754041, -0.44517196,  1.35585571,  2.24323336,
         0.99250926],
       [ 0.47397315, -1.23500724,  0.46571836, -1.6852244 , -0.36937056,
         0.99250926],
       [ 0.47397315,  0.90643609,  1.22479363,  0.77660236,  0.12826828,
         0.99250926],
       [ 0.47397315, -0.327616  ,  0.66813843, -1.54041106, -0.80480454,
        -1.00754728],
       [-0.92688082,  1.70494038, -0.69819705,  1.28344905,  1.6211848 ,
         0.99250926],
       [ 0.47397315, -0.81760727, -0.24275189, -1.6852244 , -1.17803368,
        -1.00754728],
       [-0.92688082, -0.52724207,  0.51632338, -0.67153103, -0.18275599,
         0.99250926],
       [-0.92688082,  0.2531144 , -1.30545727,  0.70419569,  0.75031683,
        -1.00754728],
       [ 0.47397315,  0.5434796 ,  0.06087822, -1.17837771, -0.61818998,
        -1.00754728],
       [-0.92688082, -0.07354645, -1.65969239,  1.13863571,  0.87472654,
        -1.00754728],
       [ 1.87482711, -1.61611156,  1.12358359, -0.59912436,  0.00385857,
         0.99250926],
       [-0.92688082, -1.05352899,  1.4272137 , -0.81634437, -0.36937056,
         0.99250926],
       [-0.92688082,  0.67051437, -1.1030372 ,  1.06622904,  0.68811198,
        -1.00754728],
       [-0.92688082, -0.327616  ,  1.17418861, -0.30949768,  0.09716585,
         0.99250926],
       [-0.92688082,  1.05161869, -0.19214687,  2.07992241,  1.87000423,
         0.99250926],
       [-0.92688082,  1.05161869, -0.64759203,  2.00751574,  2.1810285 ,
         0.99250926],
       [-0.92688082,  0.23496657, -1.71029741,  0.48697568,  0.00385857,
        -1.00754728],
       [ 1.87482711, -0.98093769, -0.09093684, -0.96115771, -1.61346766,
        -1.00754728],
       [ 0.47397315,  0.81569697,  0.16208825, -0.7439377 , -0.99141911,
         0.99250926],
       [-0.92688082,  0.65236654, -1.35606229,  0.99382237,  1.49677509,
         0.99250926],
       [ 1.87482711, -0.87205074,  1.22479363, -0.45431102,  0.5948047 ,
         0.99250926],
       [ 1.87482711, -1.34389418,  0.31390331, -1.17837771, -0.61818998,
        -1.00754728],
       [ 0.47397315,  0.48903612,  0.36450832, -0.45431102, -1.11582882,
        -1.00754728],
       [ 0.47397315,  1.48716649,  0.81995349, -0.30949768, -0.92921425,
         0.99250926],
       [-0.92688082,  0.45274047, -1.86211247,  0.63178902,  0.43929256,
        -1.00754728],
       [ 0.47397315,  0.4708883 ,  0.31390331, -0.59912436, -0.49378027,
        -1.00754728],
       [ 0.47397315, -0.92649421,  0.81995349, -0.81634437, -0.74259969,
        -1.00754728],
       [-0.92688082,  0.50718395, -0.546382  ,  0.99382237,  1.6211848 ,
         0.99250926],
       [-0.92688082, -0.52724207,  0.97176854, -0.96115771, -0.12055114,
         0.99250926],
       [-0.92688082,  0.96087957, -0.74880207,  1.13863571,  2.05661879,
         0.99250926],
       [-0.92688082,  0.23496657, -1.76090243,  0.63178902,  0.12826828,
        -1.00754728],
       [-0.92688082, -0.12798992, -1.60908738,  0.48697568,  0.47039499,
        -1.00754728],
       [-0.92688082, -0.56353772, -1.76090243,  0.9214157 ,  0.56370227,
        -1.00754728],
       [-0.92688082, -0.63612902,  0.36450832, -1.03356437, -1.24023853,
        -1.00754728],
       [ 0.47397315, -0.27317252, -0.24275189, -1.03356437, -1.05362397,
        -1.00754728],
       [ 1.87482711, -0.20058122,  0.21269327, -0.38190435,  0.62590712,
         0.99250926],
       [-0.92688082,  0.1805231 , -0.90061712,  1.35585571,  1.06134111,
         0.99250926],
       [ 0.47397315, -1.27130289, -0.34396193, -1.17837771, -0.99141911,
        -1.00754728],
       [-0.92688082, -1.12612029,  0.5669284 , -1.97485108, -0.99141911,
        -1.00754728],
       [-0.92688082,  1.17865346, -1.00182716,  1.06622904,  0.99913625,
        -1.00754728],
       [-0.92688082,  0.83384479, -0.59698702,  2.07992241,  1.99441394,
         0.99250926],
       [ 1.87482711, -1.32574636,  1.07297858, -0.59912436, -0.92921425,
        -1.00754728],
       [ 0.47397315,  0.398297  ,  0.16208825, -1.03356437, -0.68039483,
        -1.00754728],
       [-0.92688082,  0.28941005,  1.57902876, -0.7439377 ,  0.50149741,
         0.99250926],
       [ 1.87482711, -0.52724207,  0.21269327, -1.39559772, -1.24023853,
        -1.00754728],
       [-0.92688082,  0.57977525, -1.76090243,  0.9214157 ,  0.90582897,
        -1.00754728],
       [ 0.47397315,  0.65236654,  0.5669284 , -0.45431102, -0.43157541,
        -1.00754728],
       [ 1.87482711, -1.23500724,  1.12358359, -1.25078438, -0.36937056,
         0.99250926],
       [-0.92688082, -0.78131162,  0.8705585 , -1.25078438, -0.80480454,
         0.99250926],
       [-0.92688082,  1.08791434, -0.44517196,  2.07992241,  1.87000423,
         0.99250926],
       [ 0.47397315, -1.45278113,  0.31390331, -0.45431102, -0.92921425,
        -1.00754728]])

In [60]:
c = KNeighborsClassifier(n_neighbors =7)
c.fit(X_train, y_train)
y_pred = c.predict(X_val)

In [61]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_val, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_val, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_val,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[23  2  4]
 [10  4  0]
 [ 2  0 22]]
Classification Report:
              precision    recall  f1-score   support

      Adelie       0.66      0.79      0.72        29
   Chinstrap       0.67      0.29      0.40        14
      Gentoo       0.85      0.92      0.88        24

    accuracy                           0.73        67
   macro avg       0.72      0.67      0.67        67
weighted avg       0.73      0.73      0.71        67

Accuracy: 0.7313432835820896

In [62]:
from sklearn import neighbors
from sklearn.metrics import f1_score,confusion_matrix,roc_auc_score
f1_list=[]
k_list=[]
for k in range(1,10):
    clf=neighbors.KNeighborsClassifier(n_neighbors=k,n_jobs=-1)
    clf.fit(X_train,y_train)
    pred=clf.predict(X_val)
    f=f1_score(y_val,pred,average='macro')
    f1_list.append(f)
    k_list.append(k)

In [63]:
best_f1_score=max(f1_list)
best_k=k_list[f1_list.index(best_f1_score)]
print("Optimum K value=",best_k," with F1-Score=",best_f1_score)

Optimum K value= 1  with F1-Score= 0.7721176146223585

In [66]:
KNN_model=neighbors.KNeighborsClassifier(n_neighbors=1,n_jobs=-1)
KNN_model.fit(X_train,y_train)
y_new_pred=KNN_model.predict(X_val)

In [67]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:", accuracy_score(y_val, y_new_pred))
print("Precision (macro):", precision_score(y_val, y_new_pred, average='macro'))
print("Recall (macro):", recall_score(y_val, y_new_pred, average='macro'))
print("F1-Score (macro):", f1_score(y_val, y_new_pred, average='macro'))

Accuracy: 0.7910447761194029
Precision (macro): 0.7698841211202678
Recall (macro): 0.787424740010947
F1-Score (macro): 0.7721176146223585